/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlternativeRouteImport } from './routes/alternative'
import { Route as IndexRouteImport } from './routes/index'

const AlternativeRoute = AlternativeRouteImport.update({
  id: '/alternative',
  path: '/alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alternative': typeof AlternativeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alternative': typeof AlternativeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alternative': typeof AlternativeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alternative'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alternative'
  id: '__root__' | '/' | '/alternative'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlternativeRoute: typeof AlternativeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/alternative': {
      id: '/alternative'
      path: '/alternative'
      fullPath: '/alternative'
      preLoaderRoute: typeof AlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlternativeRoute: AlternativeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
